### PR TITLE
LDAP User Auth with Local Groups

### PR DESCRIPTION
**Pull request by rayvenshire**
This is a pull request related to https://github.com/tildaslash/RatticWeb/issues/299

Summarizing that issue, it'd be nice to have LDAP authentication for users with local group management as my location doesn't maintain/support meaningful LDAP groups.

One user (https://github.com/jlazic) did most of the work for this, but failed to ever make a pull request to merge this into the mainline. Additionally, they added some other features I was not interested (encrypted password and attachment fields). Those other parts have been stripped out of his fork, a few things were cleaned up and a few things were moved around to make the code compatible with the current mainline (their's was authored months ago). 

If there are issues with this, please let me know, I would prefer get this into the mainline rather than constantly maintaining a forked project.

### CODE REVIEW

**Comment by rayvenshire** [comment]
Will (re)open pull request when all the bugs are fixed and the tests are succeeding.

**Comment by smarthall** [comment]
Cool. Thanks for working on this. We are really interested in adding this feature. :smile: 

Looking forward to the updated pull request.

**Comment by Zemmiph0bia** [comment]
+1

**Comment by jlazic** [comment]
Thanks for doing this, at first I did not had enough free time to meet code quality necessary for pull request, and later I forgot about that.

**Comment by rayvenshire** [comment]
The tests are passing now; however, the current issue is that when logging in with an LDAP user, the LDAP search for attributes to update the local model fails due to an invalid basedn (i.e. null). Thus all users are only a username -- maybe that's not the end of the world. I'm poking into jlazic's code and his reference code more to see if I can figure it out.

**Comment by rayvenshire** [comment]
Reworked and removed the custom authentication backend. Now "USE_LDAP_GROUPS" controls whether or not the LDAP authentication backend saves group information for user model.

**Comment by rayvenshire** [comment]
Closing and re-opening to trigger a re-build (python 2.6 failed but due to a selenium timeout).

**Comment by rayvenshire** [comment]
Any idea about the timeline for this?

**Comment by Zemmiph0bia** [comment]
Most likely to be reviewed this weekend.

**Comment by delfick** [comment]
@smarthall @Zemmiph0bia, @hqtan and myself just tested this with our ldap at work.

It appears to work :)

The one caveat is it seems each user must sign in first before they can be assigned a group.

**Comment by rayvenshire** [comment]
If I have reasoned properly on this, it is because the user model doesn't exist until its creation at first login. When the groups come from LDAP, they are assigned to the user immediately upon user creation, so it doesn't matter; but as you pointed out, when you are using local groups, you have no reference before the first login occurs.

I'm not sure off hand, but code could probably be tweaked so that when adding members to a group, if no object exists for that reference, a new, skeletal object is created, which would then be overwritten (not the group membership, just the other aspects of the user model) on first login. It could be potentially dangerous as you might end up with a bunch of skeletons if the users never log in, but I suppose you face a similar situation for users that leave.

If this is something desired, I could poke around at it, but I make no promises. Also, I have a bunch of other projects going on at the moment, so it would be awhile. Is adding this to the mainline still feasible even with the caveat?

**Comment by Zemmiph0bia** [comment]
Thanks to everyone involved in this! Great stuff, when you get a free moment can you please add yourself to the contributors list? 
https://github.com/tildaslash/RatticWeb/wiki/RatticDB-Contributors

**Comment by marawu** [comment]
Hi, sry, but i don't understand how to add ldap user to local group. If i add in local.cfg setting ldap than disappears button "Edit". What am I doing wrong?

```
[ldap]
uri = ldap://server.example.com
binddn = uid=user,ou=Special Users,dc=example,dc=com
bindpw =
userbase = ou=People,dc=example,dc=com
userfilter = (uid=%(user)s)
groupbase = ou=groups,dc=example,dc=com
groupfilter = (&(objectClass=groupOfUniqueNames)(cn=dept))
grouptype = GroupOfUniqueNamesType
staff = cn=dept,ou=groups,dc=example,dc=com
```

**Pull request merged**
