### PR TITLE
Bootstrap 3 porting

### PR DESCRIPTION
**Pull request by Mte90**
The porting is complete, the only problems are the text field that for me is impossible add the class form-control for use the bs3 look.
I've also updated selectixe and fixed the class in the js file.

### CODE REVIEW

**Comment by Zemmiph0bia** [comment]
Hi there, 

Thank you for the pull-request, we aren't going to merge this into master. 
We're hoping that this year we'll be releasing RatticDB 2.0 and we are unlikely to bring bootstrap with us. 

Thanks, 
Eliza.

**Comment by Mte90** [comment]
I've choose Rattic, also for botostrap for create custom template with that, so this news without other information and a reject of a pr are not very a pleasure.

**Comment by ak4t0sh** [comment]
I agree with Daniele, Bootstrap is a very handy framework for template customization why would you stop using it ?

**Comment by Mte90** [comment]
bump for news

**Pull request closed without merging**
