### PR TITLE
1st class support for ssh keys

### PR DESCRIPTION
**Pull request by delfick**
Hello,

I chose to spend an internal hackday the other day adding support for ssh keys into rattic, so that I can make ssh key rotation a single command as opposed to an annoying manual process that involves generating ssh keys in amazon and putting them into rattic.

The result is this pull request.

* Adds ssh key support as a first class citizen of Cred
* Adds an expiry option to ApiKey

  * An expiry that is less than or equal to the created date is considered as not expiring
  
* Expired ApiKeys are deleted when new ones are created or are view on the profile page
* There is validation around uploading a new ssh key such that it has to be a valid ssh key
* There are tests around importing an ssh key and getting it's fingerprint
* If a password is attached to the Cred, that is used to open the ssh key if a passphrase is required
* I have added /account/generate_api_key for generating an ApiKey that expires after 5 minutes

  * GET to the url returns a 405 along with the crf cookie
  * POST to the url returns 401 if no auth is provided
  * POST with auth-username and auth-password will return 400 if it needs a token
  * POST with the token, or just username and password if that's not required will use the uploaded ssh_key to attach to the cred
  
* I have added /cred/detail/<num>/fingerprint to get the fingerprint of the ssh key attached to the cred

  * If the cred has no ssh key, a 404 is returned
  * Login is not required for this url

Thanks

Stephen.

### CODE REVIEW

**Comment by djcross** [comment]
Should the API expiry changes not be in a separate PR?  I can see value in this.

With the SSH key support, is it really Rattic's place to be able to distinguish an SSH key from any other file which could be added?  I'm not too sure about this, but can see this going down a rabbit hole of support for GPG keys, various API key formats, etc.  It's certainly a design consideration going forward.

Potentially it is worthwhile, but it may also be nice to stick with having a cred, a file, and not a lot of awareness off what these are.

**Comment by delfick** [comment]
The ssh key support is mainly so I can have the /fingerprint endpoint.

The end result of the work was so that I can manage my ssh keys without manual effort so I needed
 * API token generation (hence the temporary token idea)
 * Ability to compare fingerprints to what I have locally
 * Ability to upload and download ssh keys

Though I do see your point of going down the rabbit hole of supporting more than just ssh keys....

**Comment by delfick** [comment]
Hey @smarthall, just wondering if you've had a chance to look at this pull request?

Thanks :)

**Comment by Zemmiph0bia** [comment]
This is going to be looked at this weekend.

Thanks,
Eliza.

**Comment by delfick** [comment]
:)

**Comment by delfick** [comment]
Thankyou :)

**Comment by Zemmiph0bia** [comment]
Thank you :)

**Pull request merged**
